export const usersData = [
  {
    id: 1,
    firstName: "Jonas",
    lastName: "A",
    email: "1@g.com",
    password: "1111",
  },
  {
    id: 2,
    firstName: "Ann",
    lastName: "B",
    email: "2@g.com",
    password: "2222",
  },
  {
    id: 3,
    firstName: "John",
    lastName: "C",
    email: "3@g.com",
    password: "3333",
  },
  {
    id: 4,
    firstName: "George",
    lastName: "D",
    email: "4@g.com",
    password: "4444",
  },
  {
    id: 5,
    firstName: "Hulio",
    lastName: "E",
    email: "5@g.com",
    password: "5555",
  },
  {
    id: 6,
    firstName: "Angela",
    lastName: "F",
    email: "6@g.com",
    password: "6666",
  },
  {
    id: 7,
    firstName: "Jack",
    lastName: "J",
    email: "7@g.com",
    password: "7777",
  },
  {
    id: 8,
    firstName: "Harper",
    lastName: "H",
    email: "8@g.com",
    password: "8888",
  },
];
